Добро пожаловать, или посторонним вход воспрещён (часть 1)
htmlacademy-react/1888481-what-to-watch-9 pull request #9
Opened 2022-03-30 16:32 UTC by EvgenyJj

2022-03-31 15:48 UTC, DmitryMarkov requested changes
Показывается лишняя ошибка, надо исправить

2022-03-31 15:48 UTC, DmitryMarkov commented on project/src/services/error-handle.ts
> +        toast.info(response.data.error);
в этом случае ошибка не нужна, публичные ошибки доступны без авторизации и это нормально
![Screenshot from 2022-03-31 18-30-23](https://user-images.githubusercontent.com/9193608/161096331-cebd7dcd-2d53-4cf4-9e98-32445e99cc8a.png)

2022-03-31 15:48 UTC, DmitryMarkov commented on project/src/store/middlewares/redirect.ts
> +        if (action.type === 'game/redirectToRoute') {
название экшена из демки надо адаптировать :smile_cat:

2022-04-01 11:49 UTC, EvgenyJj commented on project/src/store/middlewares/redirect.ts
> +        if (action.type === 'game/redirectToRoute') {
ой йой, хах

2022-04-02 04:37 UTC, DmitryMarkov requested changes
Чего-то перемудрил с выполнением задания. Если myfavorites не работает страница сейчас после удаления моков, давай оставим её реализацию на будущие PR. Но так как сейчас делать не стоит, это странное решение

2022-04-02 04:37 UTC, DmitryMarkov commented on project/src/const.ts
> +  Favorite: () => '/favorite',
почему здесь функция?

2022-04-02 04:37 UTC, DmitryMarkov commented on project/src/store/action.ts
>  export const redirectToRoute = createAction<AppRoute>('game/redirectToRoute');
ну здесь-то тоже надо поменять :thinking:

2022-04-02 04:37 UTC, DmitryMarkov commented on project/src/components/user/user.tsx
> +              dispatch(fetchFavoriteFilmAction());
зачем это здесь? компонент сам должен запрашивать данные

2022-04-02 05:34 UTC, DmitryMarkov approved these changes

2022-04-02 05:34 UTC, merged